AllCops:
  TargetRubyVersion: 2.7.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Lint/MissingSuper:
  Exclude:
    - 'lib/vagrant/**/*'